# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22225b391e2226982cfd414abaa218611c9160b3f4f1b44788bb5f0e42df14e8fd34f201ef84d6438446517f536496d1c3b203be95db60fb6ef8f5bfc332b115

test:
  secret_key_base: 204a65ab6a440a27c563b15669b3d1aac56e2159b39d3a2331fe0ea6dd39bf1141d4eb02103a34edee3df3744b6b21e65d542dfdb5dc5a13076857e5b1928a17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
